Repository DEEPDIVE-BookJuck-BookJuck/BookJuck-BookJuck, pull requests merged in 2025-07, with the labels that each got.

#71 feat: 로그인 상태 및 토큰 저장 방식 개선
  src/app/(with-header)/(protected)/my-page/page.tsx
  src/app/(without-header)/auth/log-in/page.tsx
  src/lib/fetch-with-auth-server.ts
  src/lib/fetch-with-auth.ts
  src/store/auth-store.ts
Labels: feat

#73 feat: 환경 변수 수정 및 로그아웃 기능 구현
  src/common/common-header.tsx
  src/lib/auth.ts
Labels: feat

#75 style: mypage 반응형 레이아웃 구현
  src/app/(with-header)/(protected)/my-page/_components/graph.tsx
  src/app/(with-header)/(protected)/my-page/_components/recent-book-item.tsx
  src/app/(with-header)/(protected)/my-page/_components/recent-book.tsx
  src/app/(with-header)/(protected)/my-page/_components/tag-graph.tsx
  src/app/(with-header)/(protected)/my-page/page.tsx
  src/app/(with-header)/layout.tsx
Labels: feat

#87 feat: 공용 헤더 반응형 구현 및 코드 스타일 통일
  src/common/common-header.tsx
  src/lib/auth.ts
Labels: feat

#91 refactore: 마이페이지 API 호출 방식 변경 및 타이틀 변경
  src/app/(with-header)/(protected)/my-page/_components/monthly-graph.tsx
  src/app/(with-header)/(protected)/my-page/loading.tsx
  src/app/(with-header)/(protected)/my-page/page.tsx
Labels: refactor

#95 refactor: 중복타입 공통으로 분리
  src/app/(with-header)/(protected)/_types/index.ts
  src/app/(with-header)/(protected)/my-library/(detail)/[id]/page.tsx
  src/app/(with-header)/(protected)/my-library/(list)/layout.tsx
  src/app/(with-header)/(protected)/my-library/(list)/page.tsx
  src/app/(with-header)/(protected)/my-library/_components/_detail/book-thumbnail.tsx
  src/app/(with-header)/(protected)/my-library/_components/_list/library-book-item.tsx
  src/app/(with-header)/(protected)/my-page/_components/recent-book.tsx
  src/app/(with-header)/(protected)/my-page/_types/index.ts
  src/app/(with-header)/(protected)/my-page/page.tsx
  src/app/(with-header)/(protected)/profile/_components/profile-item.tsx
  src/app/(with-header)/(protected)/profile/_types/index.ts
Labels: refactor

#109 refactor: 루트 레이아웃 위치 수정 및 스타일 수정
  src/app/(with-header)/layout.tsx
  src/app/(without-header)/auth/layout.tsx
  src/app/layout.tsx
Labels: refactor

#115 feat: 커스텀 스크롤바 적용 및 404 페이지 구현
  src/app/globals.css
  src/app/not-found.tsx
Labels: feat

#130 fix: 로그인 리디렉션 오류 해결
  src/app/(with-header)/(protected)/layout.tsx
Labels: bug

#132 feat: my-page UX 개선
  src/app/(with-header)/(protected)/_components/tag-list.tsx
  src/app/(with-header)/(protected)/my-library/_components/_list/library-book-item.tsx
  src/app/(with-header)/(protected)/my-page/_components/recent-book-item.tsx
  src/app/(with-header)/(protected)/my-page/_components/recent-book.tsx
  src/app/(with-header)/(protected)/profile/_components/profile-item.tsx
Labels: feat

#134 feat: 닉네임 글자수 제한 설정
  src/app/(with-header)/(protected)/profile/_components/profile-item.tsx
Labels: feat

#137 feat: 로그인/회원가입 UI 개선
  src/app/(without-header)/auth/_components/button.tsx
  src/app/(without-header)/auth/_components/form-error.tsx
  src/app/(without-header)/auth/log-in/page.tsx
  src/app/(without-header)/auth/sign-up/page.tsx
Labels: feat

#144 feat: my-page 최근 읽은 책 라우팅 설정
  src/app/(with-header)/(protected)/my-page/_components/recent-book-item.tsx
  src/app/(with-header)/(protected)/my-page/_components/recent-book.tsx
Labels: feat

#146 feat: 모바일 사이드바 애니메이션 추가
  src/common/common-header.tsx
Labels: feat

#156 feat: main-page 스켈레톤 UI 구현 및 충돌 해결
  src/app/(with-header)/(main)/_components/skeleton/book-card-skeleton.tsx
  src/app/(with-header)/(main)/_components/skeleton/box-skeleton.tsx
  src/app/(with-header)/(main)/_components/skeleton/heading-skeleton.tsx
  src/app/(with-header)/(main)/_components/skeleton/list-page-skeleton.tsx
  src/app/(with-header)/(main)/_components/skeleton/search-skeleton.tsx
  src/app/(with-header)/(main)/page.tsx
Labels: feat
